### ISSUE TITLE
Freecodecamp Discord Link Invalid

### ISSUE THREAD

**Issue by michaelhiiva** [freeCodeCamp/contribute#217]
### Describe the Issue

The link for discord is invalid: https://discord.com/invite/freecodecamp-org-official-fi-fo-692816967895220344.

### Affected Page

https://discord.com/invite/freecodecamp-org-official-fi-fo-692816967895220344

### Steps to Reproduce

Click on the discord link in the upper right corner.

### Recommended fix or suggestions

Update the existing link for discord.

### Screenshots

![Screenshot from 2024-07-14 20-47-14](https://github.com/user-attachments/assets/32358d65-75a0-49b8-8db8-ef6f1cec0b7d)

**Comment by SaintPeter** [comment]
My recommendation is to replace the link with the "Server" link. Unlike invite links, I don't think it ever expires and it's one click from that page to join the server. It's what we're using on the Subreddit.

(Note that the URL has `sever` rather than `invite` as the first part of the slug.)

https://discord.com/servers/freecodecamp-org-official-fi-fo-692816967895220344

**Comment by karthiksneu** [comment]
@SaintPeter That does make a lot of sense.

**Comment by gikf** [comment]
Since https://chat.freecodecamp.org is redirecting to the server page, it could be used as a easy to remember replacement.

Note that there's also different link (working) to the discord in the side board. Keeping both the same might be good idea.

**Comment by karthiksneu** [comment]
Can i work on fixing this then?

**Comment by SaintPeter** [comment]
@karthiksneu We don't really assign issues here. We take the first PR that resolves the issue, so feel free to give it a go.

**Comment by gagan-bhullar-tech** [comment]
@SaintPeter created PR to fix this.

**Comment by raisedadead** [comment]
Should use: https://chat.freecodecamp.org
